import { Eye, ImageIcon } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { ptBR } from "date-fns/locale";
import type { PortalAuthor, PortalPost } from "@/data/portal";

export function Cover({ post, eager = false }: { post: PortalPost; eager?: boolean }) { return post.cover_image ? <><img src={post.cover_image} alt={post.cover_alt || post.title} loading={eager ? "eager" : "lazy"} onError={(event) => { event.currentTarget.hidden = true; event.currentTarget.nextElementSibling?.removeAttribute("hidden"); }} /><span className="portal-image-fallback" hidden><ImageIcon aria-hidden /></span></> : <span className="portal-image-fallback"><ImageIcon aria-hidden /></span>; }
export function PortalPostCard({ post, variant = "default" }: { post: PortalPost; variant?: "default" | "horizontal" | "list" }) {
  const date = post.published_at ? formatDistanceToNow(new Date(post.published_at), { addSuffix: true, locale: ptBR }) : "";
  return <article className={`portal-post-card portal-post-${variant}`} data-portal-reveal><a href={`/portal/noticia/${post.slug}`} className="portal-post-image"><Cover post={post} /></a><div className="portal-post-copy">{post.categories && <a href={`/portal/categoria/${post.categories.slug}`} className="portal-kicker">{post.categories.name}</a>}<a href={`/portal/noticia/${post.slug}`}><h3>{post.title}</h3></a>{variant === "default" && <p>{post.excerpt}</p>}<small>{post.authors?.name}{post.authors && date ? " • " : ""}{date}</small></div></article>;
}
export function FeaturedPost({ post }: { post: PortalPost }) { return <article className="portal-featured"><a href={`/portal/noticia/${post.slug}`}><Cover post={post} eager /><div className="portal-featured-overlay"><span className="portal-kicker">{post.categories?.name}</span><h1>{post.title}</h1><p>{post.excerpt}</p><small>Por {post.authors?.name} <Eye /> {post.view_count.toLocaleString("pt-BR")}</small></div></a></article>; }
export function ColumnistCard({ author }: { author: PortalAuthor }) { const initials = author.name.split(" ").slice(0, 2).map((part) => part[0]).join(""); return <a href={`/portal/colunista/${author.slug}`} className="portal-columnist-card"><span>{author.avatar_url ? <img src={author.avatar_url} alt={`Foto de ${author.name}`} /> : initials}</span><h3>{author.name}</h3><small>{author.role}</small><p>{author.headline || author.bio}</p></a>; }
export function SectionPanel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="portal-panel"><header><h2>{title}</h2>{action}</header><div>{children}</div></section>; }