import { Link } from "@tanstack/react-router";
import { ChevronRight, Eye, Mail, Mic, PlayCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { eventsService, type SiteEvent } from "@/services/eventsService";
import { portalService } from "@/services/portalService";
import type { PortalAuthor, PortalCategory, PortalPost } from "@/data/portal";
import { EXTERNAL_LINKS } from "@/config/external-links";
import { BrandMark } from "@/components/site/BrandMark";
import { ColumnistCard, FeaturedPost, PortalPostCard, SectionPanel } from "./PortalCards";
import { PortalFooter, PortalHeader } from "./PortalChrome";

export function PortalHome() {
 const [categories,setCategories]=useState<PortalCategory[]>([]), [authors,setAuthors]=useState<PortalAuthor[]>([]), [posts,setPosts]=useState<PortalPost[]>([]), [events,setEvents]=useState<SiteEvent[]>([]);
 useEffect(()=>{Promise.all([portalService.categories(),portalService.authors(),portalService.posts(),eventsService.list()]).then(([c,a,p,e])=>{setCategories(c);setAuthors(a);setPosts(p);setEvents(e.slice(0,3));});},[]);
 const q=new URLSearchParams(location.search).get("q")?.toLowerCase(); const visible=useMemo(()=>q?posts.filter(p=>`${p.title} ${p.excerpt}`.toLowerCase().includes(q)):posts,[posts,q]); const featured=visible.find(p=>p.featured)??visible[0]; const rest=visible.filter(p=>p.id!==featured?.id);
 return <div className="portal-shell"><PortalHeader categories={categories}/><main className="portal-container portal-main"><Link to="/patrocinios" className="portal-ad"><BrandMark variant="black-blue"/><span><b>Gestão completa para condomínios</b><small>Mais eficiência, menos burocracia.</small></span><ul><li>Financeiro</li><li>Cobrança</li><li>Assembleias</li></ul><strong>Conheça agora <ChevronRight/></strong></Link>{q&&<div className="portal-search-result">Resultados para “{q}” — {visible.length} notícias</div>}<section className="portal-lead-grid">{featured&&<FeaturedPost post={featured}/>}<div className="portal-secondary">{rest.slice(0,4).map(p=><PortalPostCard key={p.id} post={p} variant="horizontal"/>)}</div><SectionPanel title="Mais lidas"><ol className="portal-most-read">{[...posts].sort((a,b)=>b.view_count-a.view_count).slice(0,5).map((p,i)=><li key={p.id}><span>{i+1}</span><div><a href={`/portal/noticia/${p.slug}`}>{p.title}</a><small><Eye/> {p.view_count}</small></div></li>)}</ol></SectionPanel></section><section className="portal-category-columns">{categories.slice(0,4).map(c=><SectionPanel key={c.id} title={c.name} action={<a href={`/portal/categoria/${c.slug}`}>Ver mais <ChevronRight/></a>}><div className="portal-list">{posts.filter(p=>p.category_id===c.id).slice(0,3).map(p=><PortalPostCard key={p.id} post={p} variant="list"/>)}</div></SectionPanel>)}</section><section className="portal-modules"><SectionPanel title="Colunistas" action={<a href="/portal/colunistas">Ver mais</a>}><div className="portal-columnist-list">{authors.filter(a=>a.is_columnist).map(a=><ColumnistCard key={a.id} author={a}/>)}</div></SectionPanel><SectionPanel title="Vídeos"><a className="portal-video" href={EXTERNAL_LINKS.YOUTUBE}><span><PlayCircle/></span><b>Inteligência Artificial na gestão condominial</b></a></SectionPanel><SectionPanel title="Podcasts"><ul className="portal-podcasts">{["Inadimplência: causas e soluções","Segurança além da portaria","ESG: por onde começar?"].map(x=><li key={x}><Mic/><span>{x}</span></li>)}</ul></SectionPanel><SectionPanel title="Eventos"><ul className="portal-events">{events.map(e=><li key={e.id}><time><b>{new Date(e.starts_at).getDate()}</b><small>{new Date(e.starts_at).toLocaleDateString("pt-BR",{month:"short"})}</small></time><Link to="/eventos/$slug" params={{slug:e.slug}}><b>{e.title}</b><small>{e.city||"Online"}</small></Link></li>)}</ul></SectionPanel></section><section className="portal-partners"><b>Parceiros</b>{["Atlas Schindler","BBZ","Focus Media","CondoHuby","Damas Reis","MLG"].map(x=><span key={x}>{x}</span>)}</section><section className="portal-newsletter"><span><Mail/></span><div><h2>Receba as principais notícias do mercado condominial</h2><p>Conteúdo exclusivo do SíndicoLab, toda semana.</p></div><a href={EXTERNAL_LINKS.SUBSTACK}>Assinar newsletter</a></section></main><PortalFooter categories={categories}/></div>;
}