import { ArrowLeft, Clock, Link2, Mail } from "lucide-react";
import type { PortalAuthor, PortalCategory, PortalPost } from "@/data/portal";
import { EXTERNAL_LINKS } from "@/config/external-links";
import { LinkedinIcon } from "@/components/icons/SocialIcons";
import { Footer } from "@/components/site/Footer";
import { ColumnistCard, Cover, PortalPostCard } from "./PortalCards";
import { PortalHeader } from "./PortalChrome";

const Shell=({categories,children}:{categories:PortalCategory[];children:React.ReactNode})=><div className="portal-shell"><PortalHeader categories={categories}/><main className="portal-container portal-page">{children}</main><Footer/></div>;
export function PortalListing({title,description,posts,categories}:{title:string;description:string;posts:PortalPost[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-page-heading"><a href="/portal"><ArrowLeft/> Portal</a><h1>{title}</h1><p>{description}</p></header><div className="portal-card-grid">{posts.map(p=><PortalPostCard key={p.id} post={p}/>)}</div></Shell>}
export function PortalArticle({post,related,categories}:{post:PortalPost;related:PortalPost[];categories:PortalCategory[]}){
 const shareUrl=typeof window!=="undefined"?encodeURIComponent(window.location.href):"";
 const copyLink=()=>{if(typeof window!=="undefined")void navigator.clipboard?.writeText(window.location.href);};
 return <Shell categories={categories}><article className="portal-article"><a href="/portal" className="portal-back"><ArrowLeft/> Voltar para o Portal</a><header><a href={`/portal/categoria/${post.categories?.slug}`} className="portal-kicker">{post.categories?.name}</a><h1>{post.title}</h1><div className="portal-article-meta"><span>Por <b>{post.authors?.name}</b></span><span><Clock/> 6 min de leitura</span></div></header><div className="portal-article-cover"><Cover post={post} eager/></div><div className="portal-article-layout"><div className="portal-article-content"><p className="portal-article-deck">{post.excerpt}</p><div className="portal-article-body" dangerouslySetInnerHTML={{__html:post.content}}/><div className="portal-share"><span>Compartilhar:</span><a href={`https://www.facebook.com/sharer/sharer.php?u=${shareUrl}`} target="_blank" rel="noreferrer" aria-label="Compartilhar no Facebook"><span aria-hidden>f</span></a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${shareUrl}`} target="_blank" rel="noreferrer" aria-label="Compartilhar no LinkedIn"><LinkedinIcon/></a><button type="button" onClick={copyLink} aria-label="Copiar link"><Link2/></button></div></div><aside className="portal-article-aside">{related.length>0&&<section className="portal-panel"><header><h2>Leia também</h2></header><div className="portal-list">{related.map(p=><PortalPostCard key={p.id} post={p} variant="list"/>)}</div></section>}<section className="portal-panel portal-article-newsletter"><header><h2>Newsletter</h2></header><div><Mail/><p>Receba as principais notícias do mercado condominial.</p><a href={EXTERNAL_LINKS.SUBSTACK} target="_blank" rel="noreferrer">Assinar newsletter</a></div></section></aside></div></article></Shell>
}
export function PortalColumnists({authors,categories}:{authors:PortalAuthor[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-page-heading"><span>Opinião e análise</span><h1>Colunistas</h1><p>Especialistas que traduzem os desafios da gestão condominial.</p></header><div className="portal-columnists-grid">{authors.map(a=><ColumnistCard key={a.id} author={a}/>)}</div></Shell>}
export function PortalColumnist({author,posts,categories}:{author:PortalAuthor;posts:PortalPost[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-columnist-profile"><span>{author.avatar_url?<img src={author.avatar_url} alt={author.name}/>:author.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><small>{author.role}</small><h1>{author.name}</h1><h2>{author.headline}</h2><p>{author.bio}</p></div></header><section className="portal-related"><h2>Últimas colunas</h2><div className="portal-card-grid">{posts.map(p=><PortalPostCard key={p.id} post={p}/>)}</div></section></Shell>}