import { ArrowLeft, Clock, Share2 } from "lucide-react";
import type { PortalAuthor, PortalCategory, PortalPost } from "@/data/portal";
import { Footer } from "@/components/site/Footer";
import { ColumnistCard, Cover, PortalPostCard } from "./PortalCards";
import { PortalHeader } from "./PortalChrome";

const Shell=({categories,children}:{categories:PortalCategory[];children:React.ReactNode})=><div className="portal-shell"><PortalHeader categories={categories}/><main className="portal-container portal-page">{children}</main><Footer/></div>;
export function PortalListing({title,description,posts,categories}:{title:string;description:string;posts:PortalPost[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-page-heading"><a href="/portal"><ArrowLeft/> Portal</a><h1>{title}</h1><p>{description}</p></header><div className="portal-card-grid">{posts.map(p=><PortalPostCard key={p.id} post={p}/>)}</div></Shell>}
export function PortalArticle({post,related,categories}:{post:PortalPost;related:PortalPost[];categories:PortalCategory[]}){return <Shell categories={categories}><article className="portal-article"><header><a href={`/portal/categoria/${post.categories?.slug}`} className="portal-kicker">{post.categories?.name}</a><h1>{post.title}</h1><p>{post.excerpt}</p><div className="portal-article-meta"><span>Por <b>{post.authors?.name}</b></span><span><Clock/> 6 min de leitura</span></div></header><div className="portal-article-cover"><Cover post={post} eager/></div><div className="portal-article-layout"><aside><span>Compartilhe</span><button aria-label="Compartilhar"><Share2/></button><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(location.href)}`}>in</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(location.href)}`}>f</a></aside><div className="portal-article-body" dangerouslySetInnerHTML={{__html:post.content}}/><aside className="portal-author-box"><span>{post.authors?.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><small>Sobre o autor</small><h3>{post.authors?.name}</h3><p>{post.authors?.bio}</p>{post.authors?.is_columnist&&<a href={`/portal/colunista/${post.authors.slug}`}>Ver perfil</a>}</aside></div></article>{related.length>0&&<section className="portal-related"><h2>Leia também</h2><div className="portal-card-grid">{related.map(p=><PortalPostCard key={p.id} post={p}/>)}</div></section>}</Shell>}
export function PortalColumnists({authors,categories}:{authors:PortalAuthor[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-page-heading"><span>Opinião e análise</span><h1>Colunistas</h1><p>Especialistas que traduzem os desafios da gestão condominial.</p></header><div className="portal-columnists-grid">{authors.map(a=><ColumnistCard key={a.id} author={a}/>)}</div></Shell>}
export function PortalColumnist({author,posts,categories}:{author:PortalAuthor;posts:PortalPost[];categories:PortalCategory[]}){return <Shell categories={categories}><header className="portal-columnist-profile"><span>{author.avatar_url?<img src={author.avatar_url} alt={author.name}/>:author.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><small>{author.role}</small><h1>{author.name}</h1><h2>{author.headline}</h2><p>{author.bio}</p></div></header><section className="portal-related"><h2>Últimas colunas</h2><div className="portal-card-grid">{posts.map(p=><PortalPostCard key={p.id} post={p}/>)}</div></section></Shell>}