import { Link, useNavigate } from "@tanstack/react-router";
import { CalendarDays, Cloud, Menu, Search, X } from "lucide-react";
import { useEffect, useState } from "react";
import { BrandMark } from "@/components/site/BrandMark";
import { IconButton } from "@/components/ui/icon-button";
import { EXTERNAL_LINKS } from "@/config/external-links";
import type { PortalCategory } from "@/data/portal";

export function PortalHeader({ categories }: { categories: PortalCategory[] }) {
  const navigate = useNavigate(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [compact, setCompact] = useState(false);
  useEffect(() => { const update = () => setCompact(window.scrollY > 52); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  const date = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "2-digit", month: "long", year: "numeric" }).format(new Date());
  const search = (event: React.FormEvent) => { event.preventDefault(); const q = query.trim(); if (q) navigate({ to: "/portal", search: { q } }); setOpen(false); };
  const SearchForm = ({ mobile = false }: { mobile?: boolean }) => <form className={`portal-search ${mobile ? "portal-search-mobile" : ""}`} onSubmit={search}><input value={query} onChange={(e) => setQuery(e.target.value)} type="search" placeholder="Buscar no Portal..." aria-label="Buscar no Portal" /><button type="submit" aria-label="Buscar"><Search /></button></form>;
  return <header className={`portal-header ${compact ? "is-compact" : ""}`}><div className="portal-topbar"><div className="portal-container portal-topbar-inner"><span className="portal-live">Ao vivo</span><p>Cobertura: Encontro Nacional de Síndicos 2026 <span>• Painel: o futuro da gestão condominial</span></p><nav><Link to="/patrocinios">Anuncie</Link><a href={EXTERNAL_LINKS.SUBSTACK} target="_blank" rel="noreferrer">Newsletter</a><a href={EXTERNAL_LINKS.INSTAGRAM} target="_blank" rel="noreferrer" aria-label="Instagram">IG</a></nav></div></div><div className="portal-container portal-brandbar"><Link to="/" aria-label="Voltar à página inicial do SíndicoLab"><BrandMark variant="black-blue" responsive /></Link><div className="portal-context"><span><CalendarDays /><b>{date}</b><small>São Paulo, SP</small></span><span><Cloud /><b>23°C</b><small>Nublado</small></span></div><SearchForm /><IconButton label={open ? "Fechar menu" : "Abrir menu"} onClick={() => setOpen((value) => !value)} className="portal-menu-button">{open ? <X /> : <Menu />}</IconButton></div><nav className={`portal-nav ${open ? "is-open" : ""}`} aria-label="Editorias"><div className="portal-container"><SearchForm mobile />{categories.map((category) => <Link key={category.id} to="/portal/categoria/$slug" params={{ slug: category.slug }} onClick={() => setOpen(false)}>{category.name}</Link>)}<Link to="/portal/colunistas" onClick={() => setOpen(false)}>Colunistas</Link></div></nav></header>;
}