/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PatrociniosRouteImport } from './routes/patrocinios'
import { Route as MidiaKitRouteImport } from './routes/midia-kit'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as PortalSlugRouteImport } from './routes/portal_.$slug'
import { Route as MateriaisSlugRouteImport } from './routes/materiais_.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos_.$slug'
import { Route as AcademySolicitarAcessoRouteImport } from './routes/academy.solicitar-acesso'
import { Route as AcademyLoginRouteImport } from './routes/academy.login'
import { Route as AcademyInicioRouteImport } from './routes/academy.inicio'
import { Route as AcademyCatalogoRouteImport } from './routes/academy.catalogo'
import { Route as AcademyCursoCourseSlugRouteImport } from './routes/academy.curso.$courseSlug'
import { Route as AcademyCursoCourseSlugAprenderRouteImport } from './routes/academy.curso_.$courseSlug.aprender'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrociniosRoute = PatrociniosRouteImport.update({
  id: '/patrocinios',
  path: '/patrocinios',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaKitRoute = MidiaKitRouteImport.update({
  id: '/midia-kit',
  path: '/midia-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal_/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisSlugRoute = MateriaisSlugRouteImport.update({
  id: '/materiais_/$slug',
  path: '/materiais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos_/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySolicitarAcessoRoute = AcademySolicitarAcessoRouteImport.update({
  id: '/solicitar-acesso',
  path: '/solicitar-acesso',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLoginRoute = AcademyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyInicioRoute = AcademyInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCatalogoRoute = AcademyCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCursoCourseSlugRoute = AcademyCursoCourseSlugRouteImport.update({
  id: '/curso/$courseSlug',
  path: '/curso/$courseSlug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCursoCourseSlugAprenderRoute =
  AcademyCursoCourseSlugAprenderRouteImport.update({
    id: '/curso_/$courseSlug/aprender',
    path: '/curso/$courseSlug/aprender',
    getParentRoute: () => AcademyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/artigos': typeof ArtigosRoute
  '/blog': typeof BlogRoute
  '/cursos': typeof CursosRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/eventos': typeof EventosRoute
  '/materiais': typeof MateriaisRoute
  '/midia-kit': typeof MidiaKitRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sobre': typeof SobreRoute
  '/academy/catalogo': typeof AcademyCatalogoRoute
  '/academy/inicio': typeof AcademyInicioRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/solicitar-acesso': typeof AcademySolicitarAcessoRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/materiais/$slug': typeof MateriaisSlugRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/academy/curso/$courseSlug': typeof AcademyCursoCourseSlugRoute
  '/academy/curso/$courseSlug/aprender': typeof AcademyCursoCourseSlugAprenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/artigos': typeof ArtigosRoute
  '/blog': typeof BlogRoute
  '/cursos': typeof CursosRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/eventos': typeof EventosRoute
  '/materiais': typeof MateriaisRoute
  '/midia-kit': typeof MidiaKitRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sobre': typeof SobreRoute
  '/academy/catalogo': typeof AcademyCatalogoRoute
  '/academy/inicio': typeof AcademyInicioRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/solicitar-acesso': typeof AcademySolicitarAcessoRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/materiais/$slug': typeof MateriaisSlugRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/academy/curso/$courseSlug': typeof AcademyCursoCourseSlugRoute
  '/academy/curso/$courseSlug/aprender': typeof AcademyCursoCourseSlugAprenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/artigos': typeof ArtigosRoute
  '/blog': typeof BlogRoute
  '/cursos': typeof CursosRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/eventos': typeof EventosRoute
  '/materiais': typeof MateriaisRoute
  '/midia-kit': typeof MidiaKitRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sobre': typeof SobreRoute
  '/academy/catalogo': typeof AcademyCatalogoRoute
  '/academy/inicio': typeof AcademyInicioRoute
  '/academy/login': typeof AcademyLoginRoute
  '/academy/solicitar-acesso': typeof AcademySolicitarAcessoRoute
  '/eventos_/$slug': typeof EventosSlugRoute
  '/materiais_/$slug': typeof MateriaisSlugRoute
  '/portal_/$slug': typeof PortalSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/academy/curso/$courseSlug': typeof AcademyCursoCourseSlugRoute
  '/academy/curso_/$courseSlug/aprender': typeof AcademyCursoCourseSlugAprenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/anuncie'
    | '/artigos'
    | '/blog'
    | '/cursos'
    | '/downloads'
    | '/empresa'
    | '/eventos'
    | '/materiais'
    | '/midia-kit'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/sobre'
    | '/academy/catalogo'
    | '/academy/inicio'
    | '/academy/login'
    | '/academy/solicitar-acesso'
    | '/eventos/$slug'
    | '/materiais/$slug'
    | '/portal/$slug'
    | '/academy/'
    | '/academy/curso/$courseSlug'
    | '/academy/curso/$courseSlug/aprender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/artigos'
    | '/blog'
    | '/cursos'
    | '/downloads'
    | '/empresa'
    | '/eventos'
    | '/materiais'
    | '/midia-kit'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/sobre'
    | '/academy/catalogo'
    | '/academy/inicio'
    | '/academy/login'
    | '/academy/solicitar-acesso'
    | '/eventos/$slug'
    | '/materiais/$slug'
    | '/portal/$slug'
    | '/academy'
    | '/academy/curso/$courseSlug'
    | '/academy/curso/$courseSlug/aprender'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/anuncie'
    | '/artigos'
    | '/blog'
    | '/cursos'
    | '/downloads'
    | '/empresa'
    | '/eventos'
    | '/materiais'
    | '/midia-kit'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/sobre'
    | '/academy/catalogo'
    | '/academy/inicio'
    | '/academy/login'
    | '/academy/solicitar-acesso'
    | '/eventos_/$slug'
    | '/materiais_/$slug'
    | '/portal_/$slug'
    | '/academy/'
    | '/academy/curso/$courseSlug'
    | '/academy/curso_/$courseSlug/aprender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AdminRoute: typeof AdminRoute
  AnuncieRoute: typeof AnuncieRoute
  ArtigosRoute: typeof ArtigosRoute
  BlogRoute: typeof BlogRoute
  CursosRoute: typeof CursosRoute
  DownloadsRoute: typeof DownloadsRoute
  EmpresaRoute: typeof EmpresaRoute
  EventosRoute: typeof EventosRoute
  MateriaisRoute: typeof MateriaisRoute
  MidiaKitRoute: typeof MidiaKitRoute
  PatrociniosRoute: typeof PatrociniosRoute
  PlayRoute: typeof PlayRoute
  PortalRoute: typeof PortalRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SobreRoute: typeof SobreRoute
  EventosSlugRoute: typeof EventosSlugRoute
  MateriaisSlugRoute: typeof MateriaisSlugRoute
  PortalSlugRoute: typeof PortalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinios': {
      id: '/patrocinios'
      path: '/patrocinios'
      fullPath: '/patrocinios'
      preLoaderRoute: typeof PatrociniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia-kit': {
      id: '/midia-kit'
      path: '/midia-kit'
      fullPath: '/midia-kit'
      preLoaderRoute: typeof MidiaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/portal_/$slug': {
      id: '/portal_/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais_/$slug': {
      id: '/materiais_/$slug'
      path: '/materiais/$slug'
      fullPath: '/materiais/$slug'
      preLoaderRoute: typeof MateriaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos_/$slug': {
      id: '/eventos_/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/solicitar-acesso': {
      id: '/academy/solicitar-acesso'
      path: '/solicitar-acesso'
      fullPath: '/academy/solicitar-acesso'
      preLoaderRoute: typeof AcademySolicitarAcessoRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/login': {
      id: '/academy/login'
      path: '/login'
      fullPath: '/academy/login'
      preLoaderRoute: typeof AcademyLoginRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/inicio': {
      id: '/academy/inicio'
      path: '/inicio'
      fullPath: '/academy/inicio'
      preLoaderRoute: typeof AcademyInicioRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/catalogo': {
      id: '/academy/catalogo'
      path: '/catalogo'
      fullPath: '/academy/catalogo'
      preLoaderRoute: typeof AcademyCatalogoRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/curso/$courseSlug': {
      id: '/academy/curso/$courseSlug'
      path: '/curso/$courseSlug'
      fullPath: '/academy/curso/$courseSlug'
      preLoaderRoute: typeof AcademyCursoCourseSlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/curso_/$courseSlug/aprender': {
      id: '/academy/curso_/$courseSlug/aprender'
      path: '/curso/$courseSlug/aprender'
      fullPath: '/academy/curso/$courseSlug/aprender'
      preLoaderRoute: typeof AcademyCursoCourseSlugAprenderRouteImport
      parentRoute: typeof AcademyRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyCatalogoRoute: typeof AcademyCatalogoRoute
  AcademyInicioRoute: typeof AcademyInicioRoute
  AcademyLoginRoute: typeof AcademyLoginRoute
  AcademySolicitarAcessoRoute: typeof AcademySolicitarAcessoRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  AcademyCursoCourseSlugRoute: typeof AcademyCursoCourseSlugRoute
  AcademyCursoCourseSlugAprenderRoute: typeof AcademyCursoCourseSlugAprenderRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyCatalogoRoute: AcademyCatalogoRoute,
  AcademyInicioRoute: AcademyInicioRoute,
  AcademyLoginRoute: AcademyLoginRoute,
  AcademySolicitarAcessoRoute: AcademySolicitarAcessoRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  AcademyCursoCourseSlugRoute: AcademyCursoCourseSlugRoute,
  AcademyCursoCourseSlugAprenderRoute: AcademyCursoCourseSlugAprenderRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AdminRoute: AdminRoute,
  AnuncieRoute: AnuncieRoute,
  ArtigosRoute: ArtigosRoute,
  BlogRoute: BlogRoute,
  CursosRoute: CursosRoute,
  DownloadsRoute: DownloadsRoute,
  EmpresaRoute: EmpresaRoute,
  EventosRoute: EventosRoute,
  MateriaisRoute: MateriaisRoute,
  MidiaKitRoute: MidiaKitRoute,
  PatrociniosRoute: PatrociniosRoute,
  PlayRoute: PlayRoute,
  PortalRoute: PortalRoute,
  QuemSomosRoute: QuemSomosRoute,
  SobreRoute: SobreRoute,
  EventosSlugRoute: EventosSlugRoute,
  MateriaisSlugRoute: MateriaisSlugRoute,
  PortalSlugRoute: PortalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
