/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PatrociniosRouteImport } from './routes/patrocinios'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalSlugRouteImport } from './routes/portal_.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrociniosRoute = PatrociniosRouteImport.update({
  id: '/patrocinios',
  path: '/patrocinios',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal_/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materiais': typeof MateriaisRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/$slug': typeof PortalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/materiais': typeof MateriaisRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/$slug': typeof PortalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/materiais': typeof MateriaisRoute
  '/patrocinios': typeof PatrociniosRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRoute
  '/quem-somos': typeof QuemSomosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal_/$slug': typeof PortalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/materiais'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/portal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/materiais'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/portal/$slug'
  id:
    | '__root__'
    | '/'
    | '/materiais'
    | '/patrocinios'
    | '/play'
    | '/portal'
    | '/quem-somos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/portal_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MateriaisRoute: typeof MateriaisRoute
  PatrociniosRoute: typeof PatrociniosRoute
  PlayRoute: typeof PlayRoute
  PortalRoute: typeof PortalRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PortalSlugRoute: typeof PortalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinios': {
      id: '/patrocinios'
      path: '/patrocinios'
      fullPath: '/patrocinios'
      preLoaderRoute: typeof PatrociniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/$slug': {
      id: '/portal_/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MateriaisRoute: MateriaisRoute,
  PatrociniosRoute: PatrociniosRoute,
  PlayRoute: PlayRoute,
  PortalRoute: PortalRoute,
  QuemSomosRoute: QuemSomosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PortalSlugRoute: PortalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
